FROM php:8.0-apache

RUN echo "deb http://ftp.de.debian.org/debian buster main" >> /etc/apt/sources.list

RUN pecl install ev-beta && docker-php-ext-enable ev

RUN apt-get update && apt-get install -y libpq-dev

RUN docker-php-ext-configure pgsql -with-pgsql=/usr/local/pgsql

RUN docker-php-ext-install pdo pdo_pgsql pgsql


COPY * /var/www/html/
# CMD ["/usr/local/bin/php", "server.php"]
